-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Enum.DeploymentStatus exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-|

  - Queued -
  - Running -
  - Succeeded -
  - Failed -

-}
type DeploymentStatus
    = Queued
    | Running
    | Succeeded
    | Failed


decoder : Decoder DeploymentStatus
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "QUEUED" ->
                        Decode.succeed Queued

                    "RUNNING" ->
                        Decode.succeed Running

                    "SUCCEEDED" ->
                        Decode.succeed Succeeded

                    "FAILED" ->
                        Decode.succeed Failed

                    _ ->
                        Decode.fail ("Invalid DeploymentStatus type, " ++ string ++ " try re-running the graphqelm CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : DeploymentStatus -> String
toString enum =
    case enum of
        Queued ->
            "QUEUED"

        Running ->
            "RUNNING"

        Succeeded ->
            "SUCCEEDED"

        Failed ->
            "FAILED"
