-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (Build(..), Company(..), Deployment(..), Environment(..), Param(..), Project(..), SlackAccessToken(..), SlackChannel(..), SlackConfiguration(..), SlackProjectIntegration(..), User(..))


type Build
    = Build


type Company
    = Company


type Deployment
    = Deployment


type Environment
    = Environment


type Param
    = Param


type Project
    = Project


type SlackAccessToken
    = SlackAccessToken


type SlackChannel
    = SlackChannel


type SlackConfiguration
    = SlackConfiguration


type SlackProjectIntegration
    = SlackProjectIntegration


type User
    = User
