-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object exposing (..)


type Build
    = Build


type Company
    = Company


type Deployment
    = Deployment


type Environment
    = Environment


type Param
    = Param


type Project
    = Project


type SlackConfiguration
    = SlackConfiguration


type SlackProjectIntegration
    = SlackProjectIntegration


type User
    = User
