-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object exposing (..)


type Build
    = Build


type Deployment
    = Deployment


type Environment
    = Environment


type Param
    = Param


type Project
    = Project
