-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Query exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode exposing (Decoder)


{-| Select fields to build up a top-level query. The request can be sent with
functions from `Graphqelm.Http`.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) RootQuery
selection constructor =
    Object.selection constructor


type alias EnvironmentRequiredArguments =
    { id : String }


{-| -}
environment : EnvironmentRequiredArguments -> SelectionSet decodesTo Api.Object.Environment -> Field (Maybe decodesTo) RootQuery
environment requiredArgs object =
    Object.selectionField "environment" [ Argument.required "id" requiredArgs.id Encode.string ] object (identity >> Decode.nullable)


{-| List of projects
-}
projects : SelectionSet decodesTo Api.Object.Project -> Field (List decodesTo) RootQuery
projects object =
    Object.selectionField "projects" [] object (identity >> Decode.list)


type alias ProjectRequiredArguments =
    { id : String }


{-| -}
project : ProjectRequiredArguments -> SelectionSet decodesTo Api.Object.Project -> Field (Maybe decodesTo) RootQuery
project requiredArgs object =
    Object.selectionField "project" [ Argument.required "id" requiredArgs.id Encode.string ] object (identity >> Decode.nullable)


{-| -}
slackConfiguration : SelectionSet decodesTo Api.Object.SlackConfiguration -> Field decodesTo RootQuery
slackConfiguration object =
    Object.selectionField "slackConfiguration" [] object identity


type alias BuildsOptionalArguments =
    { page : OptionalArgument Int, pageSize : OptionalArgument Int }


{-| List of builds
-}
builds : (BuildsOptionalArguments -> BuildsOptionalArguments) -> SelectionSet decodesTo Api.Object.Build -> Field (List decodesTo) RootQuery
builds fillInOptionals object =
    let
        filledInOptionals =
            fillInOptionals { page = Absent, pageSize = Absent }

        optionalArgs =
            [ Argument.optional "page" filledInOptionals.page Encode.int, Argument.optional "pageSize" filledInOptionals.pageSize Encode.int ]
                |> List.filterMap identity
    in
    Object.selectionField "builds" optionalArgs object (identity >> Decode.list)
