-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.Build exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Build
selection constructor =
    Object.selection constructor


{-| -}
id : Field String Api.Object.Build
id =
    Object.fieldDecoder "id" [] Decode.string


{-| -}
name : Field String Api.Object.Build
name =
    Object.fieldDecoder "name" [] Decode.string


{-| -}
project : SelectionSet decodesTo Api.Object.Project -> Field decodesTo Api.Object.Build
project object =
    Object.selectionField "project" [] object identity


{-| -}
params : SelectionSet decodesTo Api.Object.Param -> Field (Maybe (List (Maybe decodesTo))) Api.Object.Build
params object =
    Object.selectionField "params" [] object (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
metadata : SelectionSet decodesTo Api.Object.Param -> Field (Maybe (List (Maybe decodesTo))) Api.Object.Build
metadata object =
    Object.selectionField "metadata" [] object (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
createdAt : Field Int Api.Object.Build
createdAt =
    Object.fieldDecoder "createdAt" [] Decode.int


{-| -}
updatedAt : Field Int Api.Object.Build
updatedAt =
    Object.fieldDecoder "updatedAt" [] Decode.int
