-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Build exposing (createdAt, id, metadata, name, params, project, selection, updatedAt)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Build
selection constructor =
    Object.selection constructor


{-| -}
id : Field String Api.Object.Build
id =
    Object.fieldDecoder "id" [] Decode.string


{-| -}
name : Field String Api.Object.Build
name =
    Object.fieldDecoder "name" [] Decode.string


{-| -}
project : SelectionSet decodesTo Api.Object.Project -> Field decodesTo Api.Object.Build
project object_ =
    Object.selectionField "project" [] object_ identity


{-| -}
params : SelectionSet decodesTo Api.Object.Param -> Field (Maybe (List (Maybe decodesTo))) Api.Object.Build
params object_ =
    Object.selectionField "params" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
metadata : SelectionSet decodesTo Api.Object.Param -> Field (Maybe (List (Maybe decodesTo))) Api.Object.Build
metadata object_ =
    Object.selectionField "metadata" [] object_ (identity >> Decode.nullable >> Decode.list >> Decode.nullable)


{-| -}
createdAt : Field Int Api.Object.Build
createdAt =
    Object.fieldDecoder "createdAt" [] Decode.int


{-| -}
updatedAt : Field Int Api.Object.Build
updatedAt =
    Object.fieldDecoder "updatedAt" [] Decode.int
