-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Deployment exposing (build, createdAt, id, selection, startedAt, status, updatedAt)

import Api.Enum.DeploymentStatus
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Deployment
selection constructor =
    Object.selection constructor


{-| -}
id : Field String Api.Object.Deployment
id =
    Object.fieldDecoder "id" [] Decode.string


{-| -}
startedAt : Field (Maybe Int) Api.Object.Deployment
startedAt =
    Object.fieldDecoder "startedAt" [] (Decode.int |> Decode.nullable)


{-| -}
status : Field Api.Enum.DeploymentStatus.DeploymentStatus Api.Object.Deployment
status =
    Object.fieldDecoder "status" [] Api.Enum.DeploymentStatus.decoder


{-| -}
build : SelectionSet decodesTo Api.Object.Build -> Field decodesTo Api.Object.Deployment
build object_ =
    Object.selectionField "build" [] object_ identity


{-| -}
createdAt : Field Int Api.Object.Deployment
createdAt =
    Object.fieldDecoder "createdAt" [] Decode.int


{-| -}
updatedAt : Field Int Api.Object.Deployment
updatedAt =
    Object.fieldDecoder "updatedAt" [] Decode.int
