-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.Deployment exposing (..)

import Api.Enum.DeploymentStatus
import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Deployment
selection constructor =
    Object.selection constructor


{-| -}
id : Field String Api.Object.Deployment
id =
    Object.fieldDecoder "id" [] Decode.string


{-| -}
startedAt : Field (Maybe Int) Api.Object.Deployment
startedAt =
    Object.fieldDecoder "startedAt" [] (Decode.int |> Decode.nullable)


{-| -}
status : Field Api.Enum.DeploymentStatus.DeploymentStatus Api.Object.Deployment
status =
    Object.fieldDecoder "status" [] Api.Enum.DeploymentStatus.decoder


{-| -}
build : SelectionSet decodesTo Api.Object.Build -> Field decodesTo Api.Object.Deployment
build object =
    Object.selectionField "build" [] object identity


{-| -}
createdAt : Field Int Api.Object.Deployment
createdAt =
    Object.fieldDecoder "createdAt" [] Decode.int


{-| -}
updatedAt : Field Int Api.Object.Deployment
updatedAt =
    Object.fieldDecoder "updatedAt" [] Decode.int
