-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Environment exposing (createdAt, environmentVariables, id, lastDeployment, name, project, selection, updatedAt)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Environment
selection constructor =
    Object.selection constructor


{-| -}
id : Field String Api.Object.Environment
id =
    Object.fieldDecoder "id" [] Decode.string


{-| -}
name : Field String Api.Object.Environment
name =
    Object.fieldDecoder "name" [] Decode.string


{-| -}
environmentVariables : SelectionSet decodesTo Api.Object.Param -> Field (List decodesTo) Api.Object.Environment
environmentVariables object_ =
    Object.selectionField "environmentVariables" [] object_ (identity >> Decode.list)


{-| -}
lastDeployment : SelectionSet decodesTo Api.Object.Deployment -> Field (Maybe decodesTo) Api.Object.Environment
lastDeployment object_ =
    Object.selectionField "lastDeployment" [] object_ (identity >> Decode.nullable)


{-| -}
project : SelectionSet decodesTo Api.Object.Project -> Field decodesTo Api.Object.Environment
project object_ =
    Object.selectionField "project" [] object_ identity


{-| -}
createdAt : Field Int Api.Object.Environment
createdAt =
    Object.fieldDecoder "createdAt" [] Decode.int


{-| -}
updatedAt : Field Int Api.Object.Environment
updatedAt =
    Object.fieldDecoder "updatedAt" [] Decode.int
