-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Project exposing (accessToken, createdAt, deploymentImage, environments, id, name, selection, slackIntegration, slug, updatedAt)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.Project
selection constructor =
    Object.selection constructor


{-| -}
id : Field String Api.Object.Project
id =
    Object.fieldDecoder "id" [] Decode.string


{-| -}
name : Field String Api.Object.Project
name =
    Object.fieldDecoder "name" [] Decode.string


{-| -}
slug : Field String Api.Object.Project
slug =
    Object.fieldDecoder "slug" [] Decode.string


{-| -}
deploymentImage : Field String Api.Object.Project
deploymentImage =
    Object.fieldDecoder "deploymentImage" [] Decode.string


{-| -}
accessToken : Field String Api.Object.Project
accessToken =
    Object.fieldDecoder "accessToken" [] Decode.string


{-| -}
environments : SelectionSet decodesTo Api.Object.Environment -> Field (List decodesTo) Api.Object.Project
environments object_ =
    Object.selectionField "environments" [] object_ (identity >> Decode.list)


{-| -}
slackIntegration : SelectionSet decodesTo Api.Object.SlackProjectIntegration -> Field (Maybe decodesTo) Api.Object.Project
slackIntegration object_ =
    Object.selectionField "slackIntegration" [] object_ (identity >> Decode.nullable)


{-| -}
createdAt : Field Int Api.Object.Project
createdAt =
    Object.fieldDecoder "createdAt" [] Decode.int


{-| -}
updatedAt : Field Int Api.Object.Project
updatedAt =
    Object.fieldDecoder "updatedAt" [] Decode.int
