-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.SlackAccessToken exposing (channels, selection, teamName)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.SlackAccessToken
selection constructor =
    Object.selection constructor


{-| -}
teamName : Field String Api.Object.SlackAccessToken
teamName =
    Object.fieldDecoder "teamName" [] Decode.string


{-| -}
channels : SelectionSet decodesTo Api.Object.SlackChannel -> Field (List decodesTo) Api.Object.SlackAccessToken
channels object_ =
    Object.selectionField "channels" [] object_ (identity >> Decode.list)
