-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.User exposing (company, createdAt, email, firstName, id, lastName, selection, updatedAt)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphql.Field as Field exposing (Field)
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.User
selection constructor =
    Object.selection constructor


{-| -}
id : Field String Api.Object.User
id =
    Object.fieldDecoder "id" [] Decode.string


{-| -}
firstName : Field String Api.Object.User
firstName =
    Object.fieldDecoder "firstName" [] Decode.string


{-| -}
lastName : Field String Api.Object.User
lastName =
    Object.fieldDecoder "lastName" [] Decode.string


{-| -}
email : Field String Api.Object.User
email =
    Object.fieldDecoder "email" [] Decode.string


{-| -}
company : SelectionSet decodesTo Api.Object.Company -> Field decodesTo Api.Object.User
company object_ =
    Object.selectionField "company" [] object_ identity


{-| -}
createdAt : Field Int Api.Object.User
createdAt =
    Object.fieldDecoder "createdAt" [] Decode.int


{-| -}
updatedAt : Field Int Api.Object.User
updatedAt =
    Object.fieldDecoder "updatedAt" [] Decode.int
