-- Do not manually edit this file, it was auto-generated by Graphqelm
-- https://github.com/dillonkearns/graphqelm


module Api.Object.User exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.Union
import Graphqelm.Field as Field exposing (Field)
import Graphqelm.Internal.Builder.Argument as Argument exposing (Argument)
import Graphqelm.Internal.Builder.Object as Object
import Graphqelm.Internal.Encode as Encode exposing (Value)
import Graphqelm.OptionalArgument exposing (OptionalArgument(Absent))
import Graphqelm.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


{-| Select fields to build up a SelectionSet for this object.
-}
selection : (a -> constructor) -> SelectionSet (a -> constructor) Api.Object.User
selection constructor =
    Object.selection constructor


{-| -}
id : Field String Api.Object.User
id =
    Object.fieldDecoder "id" [] Decode.string


{-| -}
firstName : Field String Api.Object.User
firstName =
    Object.fieldDecoder "firstName" [] Decode.string


{-| -}
lastName : Field String Api.Object.User
lastName =
    Object.fieldDecoder "lastName" [] Decode.string


{-| -}
email : Field String Api.Object.User
email =
    Object.fieldDecoder "email" [] Decode.string


{-| -}
company : SelectionSet decodesTo Api.Object.Company -> Field decodesTo Api.Object.User
company object =
    Object.selectionField "company" [] object identity


{-| -}
createdAt : Field Int Api.Object.User
createdAt =
    Object.fieldDecoder "createdAt" [] Decode.int


{-| -}
updatedAt : Field Int Api.Object.User
updatedAt =
    Object.fieldDecoder "updatedAt" [] Decode.int
